.\" start of Education
.sec
Education
.reg

.B "APEC University" " Santo Domingo, Republica Dominicana"
.br
.I "B.S. in Computer Software Engineering: January 2015 - August 2019"
.br
.I "Cumulative GPA: 3.55"

.sec
Courses
.reg

.B "Conin" " Santo Domingo, Republica Dominicana"
.br
.I "C#, ASP.NET MVC, SQL Server Course"

.B "Fundacion Codigo Libre Dominicana" " Santo Domingo, Republica Dominicana"
.br
.I "Linux Certified SysAdmin Course"
