.\" start of Experiance
.sec
Experience
.reg

.ssec "Bertrandt Group" " Getafe, Madrid, Spain"
.desc "Embedded Software Developer: Jul 2023 - Present"
.RS .\" start indentation
.experiencedesc "Provide new features to an ECU using C++ for an important europe car manufacturer. Worked on special features such as lights orchestration and automatic door opening"
.experiencedesc "As Embedded Software developer I use known automotive standards such as: AUTOSAR, SOME/IP, MISRA, CAN and LIN"
.experiencedesc "Also perform smoke tests at the Hardware ECU"
.RE .\" end indentation

.ssec "El Globo S.R.L" " Distrito Nacional, Santo Domingo"
.desc "Senior Software Engineer: February 2017 - June 2023"
.RS .\" start indentation
.experiencedesc "Make integration of functionalities for VeriFone devices with C and C++ language also integrate new functionalities and projects for importants payment processors of the country. Ported and implemented current technologies (JSON and XML Proccessing, SQLITE) that the Verifone POS weren't able to use"
.experiencedesc "As POS Software developer i work with electronic transactions standards such as: ISO8583 and EMV."
.experiencedesc "Communicate technique in multiple ways for a better understanding."
.RE .\" end indentation

.ssec "Infosyp" " Distrito Nacional, Santo Domingo"
.desc "Analysis Programmer: May 2016 - January 2017"
.RS .\" start indentation
.experiencedesc "Subsidio Estudiantil: Designed and developed an Web application to subsidize employees' children. Used MVC architectural pattern and Repository pattern."
.experiencedesc "Excelencia Estudiantil: Designed and developed another Web application to subsidize employees' children based on their academy excellence. Used MVC architectural pattern and Repository pattern."
.RE .\" end indentation
