.\" start of Projects
.sec
Projects
.reg
.br .\"line break

.ssec "QuakeWatcher (Android/Java)" "https://github.com/victordmontero/QuakeStalker"
.br
.small
An Android App that lists latests Earthquakes.
Fetches data from https://earthquake.usgs.gov/ service.
Uses Dagger DI, Data Binding, MVVM Architecture Pattern.

.ssec "AllyTalkie (Android/Java)"
.br
.small
It Uses WIFI to communicate with other peers, just like a walkie talkie.
