.\" Start Of Skills
.sec
Technical Skill
.reg

.B "Programming Languages" \
" Java, C, C++, C#, Python, Kotlin"
.sp -.5

.B "Frameworks" \
" Native Android, GTest/GMock, wxWidget"
.sp -.5

.B "Database" \
" MSSQL, MySQL, PostgreSQL, SQLite"
.sp -.5

.B "Markup" \
" HTML, XML, Markdown, XML"
.sp -.5

.B "Office Software" \
" Adobe Photoshop, Inkscape, Microsoft Office, Sketchup, Blender"
.sp -.5

.B "Operating Systems" \
" Linux, and Windows"
.sp -.5

.B "Standards" \
" ISO8583, EMV, AUTOSAR"
.sp -.5

.B Tools \
" Git, GDB, Vim, GNU Make, Cmake, NMake, Bazel"
