name: Groff CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v8
      with:
        name: resume-output
    - name: Display structure of downloaded files
      run: ls -R

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
